---
abstract: 'store sessions in a berkeleydb'
author:
  - 'Jonathan Rockway C<< <jrockway@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Remove: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
  ok: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Session-Store-BerkeleyDB
no_index:
  directory:
    - inc
    - t
requires:
  BerkeleyDB::Manager: 0
  Catalyst::Plugin::Session: 0.27
  Catalyst::Runtime: 0
  Class::Data::Inheritable: 0
  MRO::Compat: 0
  Scalar::Util: 0
  Storable: 0
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
